services:
  frontend:
    image: ghcr.io/foreverbloomstudio/foreverbloom-frontend:staging
    container_name: foreverbloom-staging-frontend
    restart: unless-stopped
    networks:
    - foreverbloom-staging-net
    volumes:
    - ./logs/frontend:/app/logs
    - ./images:/app/wwwroot/images/uploads:ro
    environment:
      ApiClient__BasePath: http://backend:8080/api/v1/
      ApiClient__ApiKeyHeaderName: ${APIKEYS_HEADERNAME}
      ApiClient__ApiKey: ${APIKEYS_FRONTENDKEYS_0}
      GoogleAnalytics__Enabled: true
      GoogleAnalytics__TrackingId: ${GOOGLEANALYTICS_TRACKINGID}
      ASPNETCORE_ENVIRONMENT: Staging
      DOTNET_ENVIRONMENT: Staging
    ports:
    - "127.0.0.1:16000:8080"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/alive"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  backend:
    image: ghcr.io/foreverbloomstudio/foreverbloom-backend:staging
    container_name: foreverbloom-staging-backend
    restart: unless-stopped
    networks:
    - foreverbloom-staging-net
    volumes:
    - ./logs/backend:/app/logs
    environment:
      ConnectionStrings__Postgres: Host=db;Port=5432;Database=${DB_DATABASE_NAME};Username=${DB_APPUSER_NAME};Password=${DB_APPUSER_PASSWORD}
      ApiKeys__HeaderName: ${APIKEYS_HEADERNAME}
      ApiKeys__FrontendKeys__0: ${APIKEYS_FRONTENDKEYS_0}
      ApiKeys__AdminKey: ${APIKEYS_ADMINKEY}
      ASPNETCORE_ENVIRONMENT: Staging
      DOTNET_ENVIRONMENT: Staging
    ports:
    - "127.0.0.1:16010:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/alive"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  db:
    image: postgres:17.5-alpine
    container_name: foreverbloom-staging-db
    restart: unless-stopped
    networks:
    - foreverbloom-staging-net
    volumes:
    - foreverbloom-staging-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_SUPERUSER_NAME}
      POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
    - "127.0.0.1:16020:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  foreverbloom-staging-net:
    driver: bridge

volumes:
  foreverbloom-staging-db-data:
    driver: local

